parameters:
    app_user.handler.locale_handler.class: App\UserBundle\Event\HandlerLocale

services:
    app_user.locale_handler:
        class: %app_user.handler.locale_handler.class%
        arguments: [%locale%, %switch_language_authorized%, %all_locales%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 66 }


    app_user.movie_voter:
        class: App\UserBundle\Security\MovieVoter
        arguments: ['@security.access.decision_manager']
        public:     false
        tags:
            - { name: security.voter }